# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python
arch:
  - arm64
  - amd64
python:
  - "3.7"

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - pip install tox

script:
  - tox 
