# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - python: 3.7
      script: tox -e py37
    - python: 3.7
      arch: arm64
      script: tox -e py37

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install virtualenv
  - pip install tox


