# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      language: generic
      env:
        - PYTHON_VERSION=3.7.9

    #- os: linux
      #language: python
      #env:
        #- PYTHON_VERSION=3.6.8


cache:
  directories:
    # scikit-ci-addons
    - $HOME/downloads

before_install:
  - |
    # Install official python distribution
    PYTHON_VERSION2=${PYTHON_VERSION%.*}
    PYTHON_VERSION1=${PYTHON_VERSION2%.*}
    curl -fsSLo /tmp/Python.pkg "https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}.tar.xz"
    sudo installer -pkg /tmp/Python.pkg -target /
    python_executable=/Library/Frameworks/Python.framework/Versions/${PYTHON_VERSION2}/bin/python${PYTHON_VERSION1}

    # Install SSL certificates
    ${python_executable} -c "import ssl; print(ssl.OPENSSL_VERSION)"
    curl -fsSLo /tmp/install_certifi.py https://github.com/joerick/cibuildwheel/raw/v1.10.0/cibuildwheel/resources/install_certifi.py
    sudo ${python_executable} /tmp/install_certifi.py

    # Install packages
    ${python_executable} -m pip install --disable-pip-version-check --upgrade pip
    # See issue https://github.com/pypa/virtualenv/issues/1638#issuecomment-587007356
    ${python_executable} -m pip install "virtualenv < 20; python_version < '3'" "virtualenv; python_version >= '3'"

    # Create and activate virtual environment
    ${python_executable} -m virtualenv ${HOME}/.pyenv/versions/${PYTHON_VERSION}
    source ${HOME}/.pyenv/versions/${PYTHON_VERSION}/bin/activate

  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test
